# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWUuS-zjx2RQ818lD49p4uQX8FUdwwMy
"""

!pip install --upgrade transformers

!pip install langchain langchain-community langchain-core chromadb sentence-transformers pypdf

from google.colab import files
uploaded = files.upload()

import os

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

documents = []

for file in os.listdir("/content"):
    if file.endswith(".pdf"):
        loader = PyPDFLoader(os.path.join("/content", file))
        documents.extend(loader.load())

print("✅ Loaded pages:", len(documents))

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

docs = splitter.split_documents(documents)

print("✅ Chunks:", len(docs))

embedding = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2"
)

print("✅ Embedding ready")

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embedding,
    persist_directory="/content/chroma_db"
)

print("✅ ChromaDB created")

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

query = "What is Agentic AI?"

results = retriever.invoke(query)

for i, r in enumerate(results):
    print(f"\nResult {i+1}:\n")
    print(r.page_content[:300])

!pip install openai langchain-openai

from google.colab import userdata
from langchain_openai import ChatOpenAI
import os

os.environ["OPENAI_API_KEY"] = "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"

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

!pip install transformers accelerate sentencepiece

from transformers import pipeline

generator = pipeline(
    "text-generation",   # ✅ IMPORTANT
    model="google/flan-t5-base",
    max_length=256
)

print("✅ Model loaded")

generator = pipeline(
    "text-generation", # Changed task to "text-generation"
    model="google/flan-t5-base",
    max_length=256
)

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

class CustomText2TextGenerator:
    def __init__(self, model, tokenizer, max_length=200):
        self.model = model
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __call__(self, text):
        inputs = self.tokenizer(text, return_tensors="pt", max_length=512, truncation=True)
        outputs = self.model.generate(**inputs, max_new_tokens=self.max_length)
        generated_text = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        return [{"generated_text": generated_text}]

generator = CustomText2TextGenerator(model, tokenizer, max_length=200)

from transformers import AutoTokenizer, AutoModelForQuestionAnswering
import torch

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased-distilled-squad")
model = AutoModelForQuestionAnswering.from_pretrained("distilbert-base-uncased-distilled-squad")

class CustomQAPipeline:
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer

    def __call__(self, question, context):
        inputs = self.tokenizer(question, context, return_tensors="pt")
        with torch.no_grad():
            outputs = self.model(**inputs)

        answer_start_scores = outputs.start_logits
        answer_end_scores = outputs.end_logits

        answer_start = torch.argmax(answer_start_scores)
        answer_end = torch.argmax(answer_end_scores) + 1

        # Fallback if no answer is found or span is invalid
        if answer_start >= answer_end or answer_start >= inputs["input_ids"].shape[1] or answer_end > inputs["input_ids"].shape[1]:
            answer = "No answer found in the context."
        else:
            answer = self.tokenizer.convert_tokens_to_string(self.tokenizer.convert_ids_to_tokens(inputs["input_ids"][0][answer_start:answer_end]))
            # Clean up special tokens like [CLS], [SEP]
            answer = answer.replace("[CLS]", "").replace("[SEP]", "").strip()
            if not answer: # If cleaning leaves an empty string
                answer = "No clear answer found in the context."

        return {"answer": answer}

qa_pipeline = CustomQAPipeline(model, tokenizer)

def generate_answer(query):
    docs = retriever.invoke(query)

    context = "\n\n".join([doc.page_content for doc in docs])

    result = generator(
        question=query,
        context=context
    )

    return result["answer"]

print(generate_answer("What is Agentic AI?"))

from typing import TypedDict, List

class AgentState(TypedDict):
    question: str
    context: str
    answer: str
    history: List[str]

def retrieve_node(state: AgentState):
    docs = retriever.invoke(state["question"])
    context = "\n\n".join([doc.page_content for doc in docs])

    return {"context": context}

def answer_node(state: AgentState):
    result = generator(
        question=state["question"],
        context=state["context"]
    )

    return {"answer": result["answer"]}

def router_node(state):
    question = state["question"].lower()

    if "what" in question or "explain" in question:
        return {"route": "retrieve"}
    else:
        return {"route": "retrieve"}

def memory_node(state: AgentState):
    history = state.get("history", [])
    history.append(state["question"])

    return {"history": history}

def eval_node(state: AgentState):
    answer = state["answer"]

    score = 0.9 if len(answer) > 10 else 0.5

    return {"score": score}

from langgraph.graph import StateGraph

graph = StateGraph(AgentState)

graph.add_node("memory", memory_node)
graph.add_node("router", router_node)
graph.add_node("retrieve", retrieve_node)
graph.add_node("answer", answer_node)
graph.add_node("eval", eval_node)

graph.set_entry_point("memory")

graph.add_edge("memory", "router")

# Conditional edge for router, moved from MNu11C5pc4St
graph.add_conditional_edges(
    "router",
    lambda state: state["route"],
    {
        "retrieve": "retrieve"
    }
)

graph.add_edge("retrieve", "answer")
graph.add_edge("answer", "eval")

app = graph.compile()

from langgraph.graph import StateGraph

graph = StateGraph(AgentState)

graph.add_node("memory", memory_node)
graph.add_node("retrieve", retrieve_node)
graph.add_node("answer", answer_node)
graph.add_node("eval", eval_node)

graph.set_entry_point("memory")

# ✅ correct flow
graph.add_edge("memory", "retrieve")
graph.add_edge("retrieve", "answer")
graph.add_edge("answer", "eval")

app = graph.compile()

result = app.invoke({
    "question": "Explain Agentic AI",
    "history": []
})

print(result)

!pip install gradio

import gradio as gr

def chat_fn(question):
    result = app.invoke({
        "question": question,
        "history": []
    })
    return result["answer"]

gr.Interface(
    fn=chat_fn,
    inputs="text",
    outputs="text",
    title="Agentic AI Assistant"
).launch()

from fastapi import FastAPI

app_api = FastAPI()

@app_api.post("/ask")
def ask(question: str):
    result = app.invoke({
        "question": question,
        "history": []
    })
    return {"answer": result["answer"]}

!pip install uvicorn nest-asyncio pyngrok

import nest_asyncio
from pyngrok import ngrok
import uvicorn

# Fix Colab loop issue
nest_asyncio.apply()

import threading
import time

ngrok.set_auth_token("3Ced3nKo7mL35oLOKpFhDBs50kc_3yE7Cdndq8WDqbDoRqEjQ") # Replace with your ngrok auth token
public_url = ngrok.connect(8000)
print("🌐 Public URL:", public_url)

def run_uvicorn():
    uvicorn.run(app_api, host="0.0.0.0", port=8000)

uvicorn_thread = threading.Thread(target=run_uvicorn)
uvicorn_thread.daemon = True
uvicorn_thread.start()

time.sleep(1) # Give the server a moment to start



